---
services:
# jenkins_slave_service
  - id: 1
    use: nagios_service
    service_description: "NRPE jenkins slave service check"
    check_command: "check_nrpe!check_jenkins"
    servicegroups: Availability

# selenium_service
  - id: 2
    use: nagios_service
    service_description: "NRPE selenium service check"
    check_command: "check_nrpe!check_selenium"
    servicegroups: Availability

# root_check
  - id: 4
    use: nagios_service
    service_description: "NRPE root disk usage check"
    check_command: "check_nrpe!check_root"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=/,data"
    servicegroups: Internals
# load_check
  - id: 98
    use: nagios_service
    service_description: "NRPE CPU usage check"
    check_command: "check_nrpe!check_load"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=load1,data&db=load5,data&db=load15,data"
    servicegroups: Internals

# memory_check
  - id: 99
    use: nagios_service
    service_description: "NRPE RAM usage check"
    check_command: "check_nrpe!check_memory"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=USED,data"
    servicegroups: Internals

nrpe_commands:
  - command_name: check_load
    plugin_name: check_load_extra
    plugin_params: "-w 1,1,1 -c 2,2,2 -r"
  - command_name: check_memory
    plugin_name: check_mem
    plugin_params: "-f -w 30 -c 10 -C"
  - command_name: check_root
    plugin_name: check_disk
    plugin_params: "-w 30% -c 10% -p /"
  - command_name: check_jenkins
    plugin_name: check_procs
    plugin_params: "-C java -a slave.jar --ereg-argument-array=-Dhost.name -c 1:"
  - command_name: check_selenium
    plugin_name: check_procs
    plugin_params: "-C java -a slave.jar --ereg-argument-array=selenium-server.*.jar -c 1:"

host_commands:

host_contacts: