---
services:
# heartbeat_service
  - id: 0
    use: nagios_service
    service_description: "NRPE heartbeat service check"
    check_command: "check_nrpe!check_heartbeat"
    servicegroups: Availability
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=procs,data&db=procs,crit_hi"

# drbd_worker_service
  - id: 1
    use: nagios_service
    service_description: "NRPE DRBD worker service check"
    check_command: "check_nrpe!check_drbd_worker"
    servicegroups: Availability
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=procs,data&db=procs,crit_hi"

# drbd_sender_service
  - id: 8
    use: nagios_service
    service_description: "NRPE DRBD sender service check"
    check_command: "check_nrpe!check_drbd_sender"
    servicegroups: Availability
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=procs,data&db=procs,crit_hi"

# drbd_receiver_service
  - id: 12
    use: nagios_service
    service_description: "NRPE DRBD receiver service check"
    check_command: "check_nrpe!check_drbd_receiver"
    servicegroups: Availability
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=procs,data&db=procs,crit_hi"

# portmapper_service
  - id: 2
    use: nagios_service
    service_description: "Portmapper TCP service check on common URI"
    check_command: "check_rpc_tcp!nfs.forgeservicelab.fi!portmapper!2,3,4"
    servicegroups: Connectivity

  - id: 3
    use: nagios_service
    service_description: "Portmapper UDP service check on common URI"
    check_command: "check_rpc_udp!nfs.forgeservicelab.fi!portmapper!2,3,4"
    servicegroups: Connectivity

# nfs_service
  - id: 4
    use: nagios_service
    service_description: "RPC nfs TCP service check on common URI"
    check_command: "check_rpc_tcp!nfs.forgeservicelab.fi!nfs!2,3,4"
    servicegroups: Connectivity

  - id: 5
    use: nagios_service
    service_description: "RPC nfs UDP service check on common URI"
    check_command: "check_rpc_udp!nfs.forgeservicelab.fi!nfs!2,3,4"
    servicegroups: Connectivity

# nlockmgr_service
  - id: 6
    use: nagios_service
    service_description: "Lockmgr TCP service check on common URI"
    check_command: "check_rpc_tcp!nfs.forgeservicelab.fi!nlockmgr!1,3,4"
    servicegroups: Connectivity

  - id: 7
    use: nagios_service
    service_description: "Lockmgr UDP service check on common URI"
    check_command: "check_rpc_udp!nfs.forgeservicelab.fi!nlockmgr!1,3,4"
    servicegroups: Connectivity

# mountd_service
  - id: 13
    use: nagios_service
    service_description: "Mountd TCP service check on common URI"
    check_command: "check_rpc_tcp!nfs.forgeservicelab.fi!mountd!1,2,3"
    servicegroups: Connectivity

  - id: 14
    use: nagios_service
    service_description: "Mountd UDP service check on common URI"
    check_command: "check_rpc_udp!nfs.forgeservicelab.fi!mountd!1,2,3"
    servicegroups: Connectivity


# 100227_service
  - id: 15
    use: nagios_service
    service_description: "100227 TCP service check on common URI"
    check_command: "check_rpc_tcp!nfs.forgeservicelab.fi!100227!2,3"
    servicegroups: Connectivity

  - id: 16
    use: nagios_service
    service_description: "100227 UDP service check on common URI"
    check_command: "check_rpc_udp!nfs.forgeservicelab.fi!100227!2,3"
    servicegroups: Connectivity

# data_check
  - id: 9
    use: nagios_service
    service_description: "NRPE disk usage check"
    check_command: "check_nrpe!check_data"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=/data,data"
    servicegroups: Internals

# updates_check
  - id: 97
    use: nagios_service
    service_description: "Pending package updates"
    check_command: "check_nrpe!check_updates"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=available_upgrades,data"
    servicegroups: Internals

# load_check
  - id: 98
    use: nagios_service
    service_description: "NRPE CPU usage check"
    check_command: "check_nrpe!check_load"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=load1,data&db=load5,data&db=load15,data"
    servicegroups: Internals

# memory_check
  - id: 99
    use: nagios_service
    service_description: "NRPE RAM usage check"
    check_command: "check_nrpe!check_memory"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=USED,data"
    servicegroups: Internals

nrpe_commands:
  - command_name: check_updates
    plugin_name: check_apt
    plugin_params: ''
  - command_name: check_load
    plugin_name: check_load_extra
    plugin_params: "-w 1,1,1 -c 2,2,2 -r"
  - command_name: check_memory
    plugin_name: check_mem
    plugin_params: "-f -w 30 -c 10 -C"
  - command_name: check_data
    plugin_name: check_disk
    plugin_params: "-w 30% -c 10%"
  - command_name: check_heartbeat
    plugin_name: check_procs
    plugin_params: "-C heartbeat -c 4:"
  - command_name: check_drbd_worker
    plugin_name: check_procs
    plugin_params: "-C drbd0_worker -c 1:"
  - command_name: check_drbd_sender
    plugin_name: check_procs
    plugin_params: "-C drbd0_asender -c 1:"
  - command_name: check_drbd_receiver
    plugin_name: check_procs
    plugin_params: "-C drbd0_receiver -c 1:"

host_commands:

host_contacts:
