---
- hosts: nagios-core
  sudo: True
  tags:
    - core
  vars:
    - is_core: True
  vars_files:
    - vars/versions.yml
  roles:
    - nagios4

- hosts: nagios-remotes
  sudo: True
  tags:
    - remotes
  vars:
    - is_core: False
  vars_files:
    - vars/versions.yml
  roles:
    - nagios4

- hosts: nagios-core
  sudo: True
  tasks:
    - set_fact:
        remote_hostname: Support
    - name: Set up Support monitoring
      include: tasks/support.yml

#    - set_fact:
#        remote_hostname: Auth
#    - name: Set up Auth monitoring
#      include: tasks/auth.yml

#    - set_fact:
#        remote_hostname: Git
#    - name: Set up Git monitoring
#      include: tasks/git.yml

- hosts: Support
  sudo: True
  tasks:
  - name: Prepare nrpe local configuration
    lineinfile:
      dest=/usr/local/nagios/etc/nrpe_local.cfg
      line="command[{{ item.command_name }}]=/usr/local/nagios/libexec/{{ item.plugin_name }} {{ item.plugin_params }}"
    with_items:
      - command_name: check_apache
        plugin_name: check_procs
        plugin_params: "-C {{ 'httpd' if ansible_distribution == 'CentOS' else 'apache2'}}"
      - command_name: check_mysql
        plugin_name: check_procs
        plugin_params: "-C mysqld"
