#roles/common
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/common.git
  path: roles/

#roles/forge_ssl
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/forge_ssl.git
  path: roles/

#roles/nagios4
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/nagios4.git
  path: roles/
