---
- hosts: nagios-core
  sudo: True
  tags:
    - core
  vars_files:
    - vars/versions.yml
  roles:
    - { role: nagios4, is_core: True }

- hosts: nagios-remotes
  sudo: True
  tags:
    - remotes
  vars_files:
    - vars/versions.yml
  roles:
    - { role: nagios4, is_core: False }
