---
- name: Load host definitions
  include_vars: support/definitions.yml

- name: Wipe temporary directory for template fragments
  file:
    path=/tmp/host
    state={{ item }}
  with_items:
    - absent
    - directory

- name: Upload Support host fragment
  template:
    src=../templates/host.cfg.j2
    dest=/tmp/host/host
  with_items:
    - "{{ host }}"

- name: Upload service fragments
  template:
    src=../templates/service.cfg.j2
    dest=/tmp/host/svc-{{ item.check_command }}
  with_items:
    - "{{ apache_service }}"
#    - check_command: check_apache
#    - check_command: check_mysql
#    - check_command: check_openfire

- name: Compose host monitoring configuration
  assemble:
    src=/tmp/host
    dest="/usr/local/nagios/etc/objects-extra/Host-{{ remote_hostname }}.cfg"
    delimiter="{{'\n'}}###################################################{{'\n\n'}}"
    owner=nagios
    group=nagios
    mode=0664

- name: Create Temporary directory for command template fragments
  file:
    path=/tmp/command
    state=directory

- name: Upload command fragments
  template:
    src=../templates/command.cfg.j2
    dest=/tmp/command/cmd-{{ item.command_name }}
  with_items:
    - command_name: check_apache
      command_line: check_nrpe -something -something
    - command_name: check_mysql
      command_line: check_nrpe -c check_myslq -something something
    - command_name: check_openfire
      command_line: check_nrpe -c check_procs -C openfire

- name: Compose command configuration
  assemble:
    src=/tmp/command
    dest="/usr/local/nagios/etc/objects-extra/Commands-{{ remote_hostname }}.cfg"
    delimiter="{{'\n'}}###################################################{{'\n\n'}}"
    owner=nagios
    group=nagios
    mode=0664
