---
- hosts: nagios-core
  sudo: True
  tags:
    - core_config
  vars_files:
    - ../host_vars/secrets.yml
    - ../host_vars/servicegroups.yml
    - ../host_vars/hostgroups.yml
    - ../host_vars/contactgroups.yml
    - ../host_vars/commands.yml
  tasks:
    - include: commoncfg.yml

    - include: ../internal-services/services.yml

    - include: ../plaza/plaza.yml

  handlers:
    - name: restart apache
      service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: restarted

- hosts: nagios-remotes
  sudo: True
  tags:
    - remotes 
  vars_files:
    - ../host_vars/{{ inventory_hostname }}.yml
  handlers:
    - include: handlers.yml
  tasks:
    - name: Prepare nrpe local configuration
      lineinfile:
        dest: /usr/local/nagios/etc/nrpe_local.cfg
        create: yes
        state: present
        regexp: ^command\[{{ item.command_name }}\].*
        line: command[{{ item.command_name }}]=/usr/local/nagios/libexec/{{ item.plugin_name }} {{ item.plugin_params }}
        owner: nagios
        group: nagios
        mode: 0664
      with_items:
        - "{{ nrpe_commands }}"
      notify:
        - restart nrpe

    - name: Allow nrpe access to nagios core
      lineinfile:
        dest: /usr/local/nagios/etc/nrpe.cfg
        regexp: ^allowed_hosts=.*
        backrefs: yes
        line: allowed_hosts={{ hostvars[item]["ansible_ssh_host"] if hostvars[item]["ansible_ssh_host"] is defined else hostvars[item]["inventory_hostname"] }},{{ hostvars[item]["ansible_default_ipv4"]["address"] }}
        state: present
      with_items:
        - "{{ groups['nagios-core'] }}"
      notify: restart nrpe

    - name: Change include statement for nrpe_local to use full path
      lineinfile:
        dest: /usr/local/nagios/etc/nrpe.cfg
        regexp: ^include=
        line: include=/usr/local/nagios/etc/nrpe_local.cfg
        state: present
      notify: restart nrpe

- hosts: nagios-core
  sudo: true
  tasks:
    - name: Re-enable notifications by default
      lineinfile:
        dest: /usr/local/nagios/etc/nagios.cfg
        regexp: ^enable_notifications
        line: enable_notifications=1
        state: present
  # Do not bounce the service after this task or notifications will start being sent for recovering services. Enable or bounce via the WebUI.
