---
commands:
  - command_name: check_nrpe
    command_line: '$USER1$/check_nrpe -H $HOSTADDRESS$ -u -c $ARG1$'
  - command_name: check_https
    command_line: '$USER1$/check_http -H $ARG1$ --ssl -w $ARG2$ -c $ARG3$ $ARG4$'
  - command_name: file-service-bug
    command_line: '$USER1$/redmine_bugs -n "$NOTIFICATIONTYPE$" -S "$SERVICEDESC$" -a "$HOSTALIAS$" -s "$SERVICESTATE$" -u "$HOSTADDRESS$" -i "$SERVICEOUTPUT$" -d "$LONGDATETIME$"'
  - command_name: file-host-bug
    command_line: '$USER1$/redmine_bugs -n "$NOTIFICATIONTYPE$" -H "$HOSTNAME$" -s "$HOSTSTATE$" -u "$HOSTADDRESS$" -i "$HOSTOUTPUT$" -d "$LONGDATETIME$"'
