---
contactgroups:
  - contactgroup_name: noone
    contactgroup_alias: Empty contact group

  - contactgroup_name: digile
    contactgroup_alias: Digile staff contact group

contacts:
  - contact_name: nobody
    contactgroups: noone
    host_notifications_enabled: 0
    service_notifications_enabled: 0
    host_notification_period: none
    service_notification_period: none
    host_notification_options: n
    service_notification_options: n
    host_notification_commands: notify-host-by-email
    service_notification_commands: notify-service-by-email
