---
host:
  - use: nagios_host
    address: "{{ hostvars[target_inventory_hostname]['ansible_ssh_host'] if hostvars[target_inventory_hostname]['ansible_ssh_host'] is defined else hostvars[target_inventory_hostname]['inventory_hostname'] }}"
    alias: FORGE Database Server
    display_name: DBserver
    hostgroups: others

services:
  - id: 15 
    use: nagios_service
    service_description: "NRPE postgresql service check"
    check_command: "check_nrpe!check_postgresql"
    servicegroups: Availability
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=procs,data&db=procs,crit_hi"

  - id: 16
    use: nagios_service
    service_description: "NRPE postgresql WAL service check"
    check_command: "check_nrpe!check_postgresql_wal"
    servicegroups: Availability
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=procs,data&db=procs,crit_hi"

# root_check
  - id: 9
    use: nagios_service
    service_description: "NRPE disk usage check"
    check_command: "check_nrpe!check_root"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=/data,data"
    servicegroups: Internals

# load_check
  - id: 10
    use: nagios_service
    service_description: "NRPE CPU usage check"
    check_command: "check_nrpe!check_load"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=load1,data&db=load5,data&db=load15,data"
    servicegroups: Internals

# memory_check
  - id: 11
    use: nagios_service
    service_description: "NRPE RAM usage check"
    check_command: "check_nrpe!check_memory"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=USED,data"
    servicegroups: Internals

  - id: 13
    use: nagios_service
    service_description: "PostgreSQL local connectivity check"
    check_command: "check_nrpe!check_conn_postgresql"
    servicegroups: Internals

nrpe_commands:
  - command_name: check_root
    plugin_name: check_disk
    plugin_params: "-w 30% -c 10% -p /"
  - command_name: check_load
    plugin_name: check_load_extra
    plugin_params: "-w 1,1,1 -c 2,2,2 -r"
  - command_name: check_memory
    plugin_name: check_mem
    plugin_params: "-f -w 30 -c 10 -C"
  - command_name: check_postgresql
    plugin_name: check_procs
    plugin_params: "-C postgres -c 2:"
  - command_name: check_postgresql_wal
    plugin_name: check_procs
    plugin_params: "-C postgres -a 'wal sender' -c 1:"
  - command_name: check_conn_postgresql
    plugin_name: check_postgresql
    plugin_params: "postgres"
