---
host:
  - use: nagios_host
    address: "{{ hostvars[target_inventory_hostname]['ansible_ssh_host'] if hostvars[target_inventory_hostname]['ansible_ssh_host'] is defined else hostvars[target_inventory_hostname]['inventory_hostname'] }}"
    alias: "Plaza {{ target_inventory_hostname }}"
    display_name: "Plaza {{ target_inventory_hostname }}"
    hostgroups: plaza
    icon_image: "{{ hostvars[target_inventory_hostname]['ansible_distribution'] }}.png"
    statusmap_image: haproxy.gd2
    2d_coords: 620.0,150.0
