---
host:
  - use: nagios_host
    address: "{{ hostvars[target_inventory_hostname]['ansible_ssh_host'] if hostvars[target_inventory_hostname]['ansible_ssh_host'] is defined else hostvars[target_inventory_hostname]['inventory_hostname'] }}"
    alias: Replication host
    display_name: Replicator
    hostgroups: others
    icon_image: "{{ hostvars[target_inventory_hostname]['ansible_distribution'] }}.png"
    statusmap_image: database.gd2
    2d_coords: 245.0,260.0
    parents: dbserver, git, ci, nfs01, nfs02

services:
  - id: 0
    use: nagios_service
    service_description: "NRPE mysql service check"
    check_command: "check_nrpe!check_mysql"
    servicegroups: Availability
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=procs,data&db=procs,crit_hi"

  - id: 15 
    use: nagios_service
    service_description: "NRPE postgresql service check"
    check_command: "check_nrpe!check_postgresql"
    servicegroups: Availability
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=procs,data&db=procs,crit_hi"

  - id: 16
    use: nagios_service
    service_description: "NRPE postgresql WAL service check"
    check_command: "check_nrpe!check_postgresql_wal"
    servicegroups: Availability
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=procs,data&db=procs,crit_hi"

  - id: 1
    use: nagios_service
    service_description: "MySQL Database snapshot age"
    check_command: "check_nrpe!check_mysql_database"
    servicegroups: Availability

  - id: 14
    use: nagios_service
    service_description: "PostgreSQL Database snapshot age"
    check_command: "check_nrpe!check_postgresql_database"
    servicegroups: Availability

  - id: 2
    use: nagios_service
    service_description: "Filesystem snapshot age"
    check_command: "check_nrpe!check_filesystem"
    servicegroups: Availability

# data_check
  - id: 9
    use: nagios_service
    service_description: "NRPE disk usage check"
    check_command: "check_nrpe!check_data"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=/data,data"
    servicegroups: Internals

# load_check
  - id: 10
    use: nagios_service
    service_description: "NRPE CPU usage check"
    check_command: "check_nrpe!check_load"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=load1,data&db=load5,data&db=load15,data"
    servicegroups: Internals

# memory_check
  - id: 11
    use: nagios_service
    service_description: "NRPE RAM usage check"
    check_command: "check_nrpe!check_memory"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=USED,data"
    servicegroups: Internals

# replication_check
  - id: 12
    use: nagios_service
    service_description: "MySQL replication check"
    check_command: "check_nrpe!check_repl_mysql"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPoput()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=seconds behind master,data"
    servicegroups: Internals

  - id: 13
    use: nagios_service
    service_description: "PostgreSQL replication check"
    check_command: "check_nrpe!check_repl_postgresql"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPoput()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=delay,data"
    servicegroups: Internals

nrpe_commands:
  - command_name: check_data
    plugin_name: check_disk
    plugin_params: "-w 30% -c 10% -p /data"
  - command_name: check_load
    plugin_name: check_load_extra
    plugin_params: "-w 1,1,1 -c 2,2,2 -r"
  - command_name: check_memory
    plugin_name: check_mem
    plugin_params: "-f -w 30 -c 10 -C"
  - command_name: check_mysql
    plugin_name: check_procs
    plugin_params: "-C mysqld -c 1:"
  - command_name: check_postgresql
    plugin_name: check_procs
    plugin_params: "-C postgres -c 2:"
  - command_name: check_postgresql_wal
    plugin_name: check_procs
    plugin_params: "-C postgres -a 'wal receiver' -c 1:"
  - command_name: check_mysql_database
    plugin_name: check_file_age
    plugin_params: "-f /data/database_snapshots/plaza -w 86400 -c 172800"
  - command_name: check_postgresql_database
    plugin_name: check_file_age
    plugin_params: "-f /data/database_snapshots/dbserver -w 86400 -c 172800"
  - command_name: check_filesystem
    plugin_name: check_file_age
    plugin_params: "-f /data/filesystem_snapshots -w 86400 -c 172800"
  - command_name: check_repl_mysql
    plugin_name: check_mysql
    plugin_params: "-S -u root -w 60 -c 300"
  - command_name: check_repl_postgresql
    plugin_name: check_postgresql
    plugin_params: "postgres -r -w 60 -c 300"

host_commands:

host_contacts:
