---
servicegroups:
  - servicegroup_name: Connectivity
    servicegroup_alias: Service Connectivity Checks
    notes: This group holds the checks to verify connectivity to services from outside the monitored host itself.

  - servicegroup_name: Availability
    servicegroup_alias: Service Internal Availability Checks
    notes: This group holds the checks to verify internally on the monitored host that the offered services are running.

  - servicegroup_name: Internals
    servicegroup_alias: CPU / MEM / DISK checks

servicetemplates:
  - name: nagios_service
    max_check_attempts: 3
    check_interval: 5
    retry_interval: 1
    check_period: 24x7
    notification_interval: 0
    notification_period: 24x7
    contacts: redmine
    contact_groups: noone
    register: 0
