---
host:
  - use: nagios_host
    address: support.forgeservicelab.fi
    alias: Forge ServiceLab Support
    display_name: Support Machine

services:
# apache_service
  - id: 0
    use: nagios_service
    service_description: "NRPE apache service check"
    check_command: "check_nrpe!check_apache"
    servicegroups: Availability

# mysql_service
  - id: 1
    use: nagios_service
    service_description: "NRPE mysql service check"
    check_command: "check_nrpe!check_mysql"
    servicegroups: Availability

# xmpp_service
  - id: 2
    use: nagios_service
    service_description: "NRPE jabber service check"
    check_command: "check_nrpe!check_jabber"
    servicegroups: Availability

# redmine_check
  - id: 7
    use: nagios_service
    service_description: "Redmine application connectivity check"
    check_command: 'check_https!support.forgeservicelab.fi!5!10!-u /redmine -d redmine/login -e 302'
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=time,data"
    servicegroups: Connectivity

# password_check
  - id: 8
    use: nagios_service
    service_description: "Password recovery application connectivity check"
    check_command: 'check_https!support.forgeservicelab.fi!5!10!-u /password/ -e 200'
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=time,data"
    servicegroups: Connectivity

# xmpp_check
  - id: 3
    use: nagios_service
    service_description: "Jabber connectivity check"
    check_command: 'check_jabber!xmpp.forgeservicelab.fi!5222!xmlns:stream=\"http://etherx.jabber.org/streams\"\ xmlns=\"jabber:client\"\ from=\"xmpp.forgeservicelab.fi\"'
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=time,data"
    servicegroups: Connectivity

# root_check
  - id: 4
    use: nagios_service
    service_description: "NRPE root disk usage check"
    check_command: "check_nrpe!check_root"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=/,data"
    servicegroups: Internals

# load_check
  - id: 5
    use: nagios_service
    service_description: "NRPE CPU usage check"
    check_command: "check_nrpe!check_load"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=load1,data&db=load5,data&db=load15,data"
    servicegroups: Internals

# memory_check
  - id: 6
    use: nagios_service
    service_description: "NRPE RAM usage check"
    check_command: "check_nrpe!check_memory"
    action_url: "/nagios/cgi-bin/show.cgi?host=$HOSTNAME$&service=$SERVICEDESC$' onMouseOver='showGraphPopup(this)' onMouseOut='hideGraphPopup()' rel='/nagios/cgi-bin/showgraph.cgi?host=$HOSTNAME$&service=$SERVICEDESC$&db=USED,data"
    servicegroups: Internals

nrpe_commands:
  - command_name: check_apache
    plugin_name: check_procs
    plugin_params: "-C httpd -c 1:"
  - command_name: check_mysql
    plugin_name: check_procs
    plugin_params: "-C mysqld -c 1:"
  - command_name: check_jabber
    plugin_name: check_procs
    plugin_params: "--ereg-argument-array=.*openfire.* -c 1:"
  - command_name: check_root
    plugin_name: check_disk
    plugin_params: "-w 30% -c 10% -p /"
  - command_name: check_load
    plugin_name: check_load_extra
    plugin_params: "-w 1,1,1 -c 2,2,2 -r"
  - command_name: check_memory
    plugin_name: check_mem
    plugin_params: "-f -w 30 -c 10 -C"

commands:
  - command_name: check_jabber
    command_line: '$USER1$/check_jabber -H $ARG1$ -p $ARG2$ -e $ARG3$'

# Contact definitions for Support host only:
contacts:
#  - contact_name: nobody
#    contactgroups: noone
#    host_notifications_enabled: 0
#    service_notifications_enabled: 0
#    host_notification_period: none
#    service_notification_period: none
#    host_notification_options: n
#    service_notification_options: n
#    host_notification_commands: notify-host-by-email
#    service_notification_commands: notify-service-by-email
